USE GuitarApp
go
BEGIN

---danh sach dan
SELECT MADAN, MDLDAN
FROM GUITAR

--liet ke dan va loai dan tuong ung
SELECT MADAN, MDLDAN, TENLOAI
FROM GUITAR
INNER JOIN LOAIDAN
ON dbo.GUITAR.MALOAI=dbo.LOAIDAN.MALOAI
--hien thi thong tin dan chua ban duoc

SELECT MADAN, MDLDAN,SLTON
FROM GUITAR
WHERE MADAN NOT IN(
SELECT MADAN FROM HDX)

--hien thi thong tin va so luong ban cua dan Ban chay nhat
SELECT TOP 1 MDLDAN,SUM(SLX)
FROM GUITAR G,HDX H
WHERE H.MADAN=G.MADAN
GROUP BY MDLDAN
ORDER BY SUM(SLX)DESC
--xuat ra so hoa don cua khach hang (duoc nhap tu ban phim) va tinh tong tien cua tung hoa don
SELECT TENKH, COUNT(SOHDX) AS SOLANMUA, SUM(SLX*DGX) AS TONGDONGIA
FROM HDX,KH 
WHERE dbo.HDX.MAKH=dbo.KH.MAKH
GROUP BY TENKH

--tim xuat theo hieu loai go top/back/side/fing

SELECT TENHIEU,TENTOP,TENSIDE,TENBACK ,TENNECK, TENFING ,ELE
FROM HIEUDAN H, THONGSO T, GOTOP P, GOBACK B, GOFING F, GOSIDE S, GUITAR G,GONECK N
WHERE H.MAHIEU = G.MAHIEU
AND T.MATOP=P.MATOP
AND T.MABACK=B.MABACK
AND T.MAFING=F.MAFING
AND T.MASIDE=S.MASIDE
AND T.MADAN=G.MADAN
AND T.MANECK=N.MANECK
ORDER BY TENHIEU ASC

--KH VIP
ALTER PROC VIP  
AS
BEGIN
	SELECT K.MAKH,TENKH,DCKH,DTKH,EMKH
	INTO KH_VIP
	FROM KH K, HDX H
	WHERE K.MAKH=H.MAKH
	GROUP BY K.MAKH,TENKH,DCKH,DTKH,EMKH
	HAVING SUM (SLX*DGX)>=10000000
	SELECT * FROM KH_VIP
END
VIP

-- update so luong ton 
ALTER PROC SLT
AS 
BEGIN
	UPDATE GUITAR
	SET SLTON=(SELECT SLTON=SUM(SLTON+SLN)
		    FROM GUITAR G,HDN H
		    WHERE G.MADAN=H.MADAN)
END 
SLT